-- MySQL Script generated by MySQL Workbench
-- Sat Jun 16 12:35:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MusicDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MusicDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MusicDB` DEFAULT CHARACTER SET utf8 ;
USE `MusicDB` ;

-- -----------------------------------------------------
-- Table `MusicDB`.`Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicDB`.`Artists` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Url` VARCHAR(45) NOT NULL,
  `Genius` VARCHAR(45) NOT NULL,
  `Instagram` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `Twitter` VARCHAR(45) NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicDB`.`Songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicDB`.`Songs` (
  `Id` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Url` VARCHAR(45) NOT NULL,
  `ArtistId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Song_Artist_idx` (`ArtistId` ASC),
  CONSTRAINT `fk_Song_Artist`
    FOREIGN KEY (`ArtistId`)
    REFERENCES `MusicDB`.`Artists` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicDB`.`Users` (
  `Id` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicDB`.`Users_has_Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicDB`.`Users_has_Artists` (
  `UserId` INT NOT NULL,
  `ArtistId` INT NOT NULL,
  PRIMARY KEY (`UserId`, `ArtistId`),
  INDEX `fk_User_has_Artist_Artist1_idx` (`ArtistId` ASC),
  INDEX `fk_User_has_Artist_User1_idx` (`UserId` ASC),
  CONSTRAINT `fk_User_has_Artist_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `MusicDB`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Artist_Artist1`
    FOREIGN KEY (`ArtistId`)
    REFERENCES `MusicDB`.`Artists` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicDB`.`Users_has_Songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicDB`.`Users_has_Songs` (
  `UserId` INT NOT NULL,
  `SongId` INT NOT NULL,
  PRIMARY KEY (`UserId`, `SongId`),
  INDEX `fk_User_has_Song_Song1_idx` (`SongId` ASC),
  INDEX `fk_User_has_Song_User1_idx` (`UserId` ASC),
  CONSTRAINT `fk_User_has_Song_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `MusicDB`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Song_Song1`
    FOREIGN KEY (`SongId`)
    REFERENCES `MusicDB`.`Songs` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO Artists (Id, Name, Url, Genius, Instagram, Facebook, Twitter, CreatedAt, UpdatedAt)
VALUES (1, 'Artist', 'artist.com', 'G', 'Ig', 'Fb', 'Tw', NOW(), NOW());

INSERT INTO Songs (Id, Title, Url, ArtistId, CreatedAt, UpdatedAt)
VALUES (1, 'Song', 'song.com', 1, NOW(), NOW());